Upgrade pyyaml in lock file to fix error
pyyaml 6.0.0 gives this error:

    AttributeError: cython_sources

    Note: This error originates from the build backend, and is likely not a problem with poetry but with PyYAML (6.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pyyaml (==6.0)"'.

This error is fixed by upgrading to pyyaml 6.0.1